//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.Office.Comments.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.Office.Comments.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Returns the sum of two numbers..
        /// </summary>
        public static string ChildActivityDescription {
            get {
                return ResourceManager.GetString("ChildActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Child Activity.
        /// </summary>
        public static string ChildActivityDisplayName {
            get {
                return ResourceManager.GetString("ChildActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The first number..
        /// </summary>
        public static string ChildActivityFirstNumberDescription {
            get {
                return ResourceManager.GetString("ChildActivityFirstNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FirstNumber.
        /// </summary>
        public static string ChildActivityFirstNumberDisplayName {
            get {
                return ResourceManager.GetString("ChildActivityFirstNumberDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The second number..
        /// </summary>
        public static string ChildActivitySecondNumberDescription {
            get {
                return ResourceManager.GetString("ChildActivitySecondNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SecondNumber.
        /// </summary>
        public static string ChildActivitySecondNumberDisplayName {
            get {
                return ResourceManager.GetString("ChildActivitySecondNumberDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The sum of the two input numbers..
        /// </summary>
        public static string ChildActivitySumDescription {
            get {
                return ResourceManager.GetString("ChildActivitySumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sum.
        /// </summary>
        public static string ChildActivitySumDisplayName {
            get {
                return ResourceManager.GetString("ChildActivitySumDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract comment author. Column name &quot;Author&quot;..
        /// </summary>
        public static string ExtractAuthorDescription {
            get {
                return ResourceManager.GetString("ExtractAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract Author.
        /// </summary>
        public static string ExtractAuthorDisplayName {
            get {
                return ResourceManager.GetString("ExtractAuthorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract comment text. Column name &quot;Comment&quot;..
        /// </summary>
        public static string ExtractCommentDescription {
            get {
                return ResourceManager.GetString("ExtractCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract Comment.
        /// </summary>
        public static string ExtractCommentDisplayName {
            get {
                return ResourceManager.GetString("ExtractCommentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract comment date. Column name &quot;Date&quot;..
        /// </summary>
        public static string ExtractDateDescription {
            get {
                return ResourceManager.GetString("ExtractDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract Date.
        /// </summary>
        public static string ExtractDateDisplayName {
            get {
                return ResourceManager.GetString("ExtractDateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract comment scope. This is the text highlighted. Column name &quot;Scope&quot;..
        /// </summary>
        public static string ExtractScopeDescription {
            get {
                return ResourceManager.GetString("ExtractScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract Scope.
        /// </summary>
        public static string ExtractScopeDisplayName {
            get {
                return ResourceManager.GetString("ExtractScopeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hint.
        /// </summary>
        public static string ExtractWordCommentsPathHintText {
            get {
                return ResourceManager.GetString("ExtractWordCommentsPathHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document path (String). Text must be quoted..
        /// </summary>
        public static string FilePathDescription {
            get {
                return ResourceManager.GetString("FilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document path &lt;String&gt;.
        /// </summary>
        public static string FilePathDisplayName {
            get {
                return ResourceManager.GetString("FilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide a value for {0}..
        /// </summary>
        public static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options (Extraction columns).
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent Scope.
        /// </summary>
        public static string ParentScope {
            get {
                return ResourceManager.GetString("ParentScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contains and authenticates all child activities..
        /// </summary>
        public static string ParentScopeDescription {
            get {
                return ResourceManager.GetString("ParentScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction result (DataTable). Based on the Extraction Options selected, the result will have different column number (e.g: To access Comment colomn use Result[&quot;Date&quot;])..
        /// </summary>
        public static string ResultDescription {
            get {
                return ResourceManager.GetString("ResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result &lt;DataTable&gt;.
        /// </summary>
        public static string ResultDisplayName {
            get {
                return ResourceManager.GetString("ResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activity is only valid inside a Parent Scope..
        /// </summary>
        public static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
    }
}
